export const allContracts = [
  {
    name: "general-client-agreements",
    type: "generalClientAgreements",
    title: "General Client Agreements",
    short: "GCA",
    info: {
      description: [
        "These General Client Agreements (GCA) outline the key terms and conditions that businesses agree to when they hire our services. By accepting these agreements, you agree to comply with all the terms and conditions outlined in the GCA, as well as to provide us with the necessary information and materials to complete our work.",
        "By accepting the GCA, you are agreeing to the following terms and conditions:",
        "- Our services will be performed in accordance with the GCA and any additional terms and conditions provided by us.",
        "- We will provide you with all necessary information and materials to complete our work.",
        "- We will not hold you responsible for any errors, omissions, or inaccuracies in the information provided to us.",
        "- You will be responsible for all costs associated with our services, including any fees, expenses, and other charges.",
      ],
      detail: "",
      short: "",
      intro: "",
      subContracts: [
        "master-service-agreement-msa",
        "privacy-policy-agreement",
        "service-agreement",
        "non-disclosure-agreement-nda",
        "non-compete-agreement",
        "independent-contractor-agreement",
        "copyright-and-licensing-agreement",
        "trademark-usage-agreement",
        "affiliate-and-referral-agreement",
      ],
    },
  },
  {
    name: "digital-and-web-development-contracts",
    type: "digitalAndWebDevelopmentContracts",
    title: "Digital and Web Development Contracts",
    short: "DWDC",
    info: {
      description: [
        "These Digital and Web Development Contracts (DWDC) outline the key terms and conditions that businesses agree to when they hire our web development services. By accepting these agreements, you agree to comply with all the terms and conditions outlined in the DWDC, as well as to provide us with the necessary information and materials to complete our work.",
        "By accepting the DWDC, you are agreeing to the following terms and conditions:",
        "- Our web development services will be performed in accordance with the DWDC and any additional terms and conditions provided by us.",
        "- We will provide you with all necessary information and materials to complete our work.",
        "- We will not hold you responsible for any errors, omissions, or inaccuracies in the information provided to us.",
        "- You will be responsible for all costs associated with our web development services, including any fees, expenses, and other charges.",
      ],
      detail: "",
      short: "",
      intro: "",
      subContracts: [
        "web-development-agreement",
        "e-commerce-development-agreement",
        "single-page-application-spa-development-agreement",
        "wireframing-and-prototyping-agreement",
        "database-management-and-optimization-contract",
        "it-support-and-maintenance-agreement",
      ],
    },
  },
  {
    name: "content-and-marketing-contracts",
    type: "contentAndMarketingContracts",
    title: "Content and Marketing Contracts",
    short: "CMDC",
    info: {
      description: [
        "These Content and Marketing Contracts (CMDC) outline the key terms and conditions that businesses agree to when they hire our content creation and marketing services. By accepting these agreements, you agree to comply with all the terms and conditions outlined in the CMDC, as well as to provide us with the necessary information and materials to complete our work.",
        "By accepting the CMDC, you are agreeing to the following terms and conditions:",
        "- Our content creation and marketing services will be performed in accordance with the CMDC and any additional terms and conditions provided by us.",
        "- We will provide you with all necessary information and materials to complete our work.",
        "- We will not hold you responsible for any errors, omissions, or inaccuracies in the information provided to us.",
        "- You will be responsible for all costs associated with our content creation and marketing services, including any fees, expenses, and other charges.",
      ],
      detail: "",
      short: "",
      intro: "",
      subContracts: [
        "seo-service-agreement",
        "content-creation-agreement",
        "brand-storytelling-and-copywriting",
        "marketing-strategy-and-consultation",
        "technical-writing-agreement",
        "training-materials-and-course-development-agreement",
        "product-guide-and-manual-agreement",
      ],
    },
  },
  {
    name: "payment-and-sales-contracts",
    type: "paymentAndSalesContracts",
    title: "Payment and Sales Contracts",
    short: "PS",
    info: {
      description: [
        "These Payment and Sales Contracts (PS) outline the key terms and conditions that businesses agree to when they hire our payment and sales services. By accepting these agreements, you agree to comply with all the terms and conditions outlined in the PS, as well as to provide us with the necessary information and materials to complete our work.",
        "By accepting the PS, you are agreeing to the following terms and conditions:",
        "- Our payment and sales services will be performed in accordance with the PS and any additional terms and conditions provided by us.",
        "- We will provide you with all necessary information and materials to complete our work.",
        "- We will not hold you responsible for any errors, omissions, or inaccuracies in the information provided to us.",
        "- You will be responsible for all costs associated with our payment and sales services, including any fees, expenses, and other charges.",
      ],
      detail: "",
      short: "",
      intro: "",
      subContracts: [
        "invoice-payment-terms-agreement",
        "retainer-agreement",
        "subscription-and-recurring-payment-agreement",
      ],
    },
  },
  {
    name: "website-and-digital-policy-agreements",
    type: "websiteAndDigitalPolicyAgreements",
    title: "Website and Digital Policy Agreements",
    short: "WDPA",
    info: {
      description: [
        "These Website and Digital Policy Agreements (WDPA) outline the key terms and conditions that businesses agree to when they hire our website and digital policy services. By accepting these agreements, you agree to comply with all the terms and conditions outlined in the WDPA, as well as to provide us with the necessary information and materials to complete our work.",
        "By accepting the WDPA, you are agreeing to the following terms and conditions:",
        "- Our website and digital policy services will be performed in accordance with the WDPA and any additional terms and conditions provided by us.",
        "- We will provide you with all necessary information and materials to complete our work.",
        "- We will not hold you responsible for any errors, omissions, or inaccuracies in the information provided to us.",
      ],
      detail: "",
      short: "",
      intro: "",
      subContracts: [],
    },
  },
];
