import { NavSidebar } from "@/components/NavSidebar";
import {
  SidebarProvider,
  SidebarTrigger,
  useSidebar,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { NotFoundProvider, useNotFound } from "./context/NotFoundContext";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NotFoundProvider>
        <SidebarProvider>
          <Providers>
            <MainContent>{children}</MainContent>
          </Providers>
        </SidebarProvider>
      </NotFoundProvider>
    </html>
  );
}

const MainContent = ({ children }: { children: React.ReactNode }) => {
  const { isNotFound } = useNotFound();
  const { open } = useSidebar();
  return (
    <>
      {!isNotFound && (
        <>
          <NavSidebar />
          <SidebarTrigger
            className={
              open
                ? "py-10 pl-5 pr-4 sticky top-5 hover:border-none"
                : "py-10 pl-10 pr-4 sticky top-5 hover:border-none"
            }
          />
        </>
      )}
      <main className="relative w-11/12 mx-auto py-10 pr-5">{children}</main>
    </>
  );
};
